### ISSUE TITLE
המצלמה צריכה להסתובב עם השחקן

### ISSUE THREAD

**Issue by erelsgl** [Game-Developmento/bark-away#1]
א. כשהכלב מסתובב, המצלמה צריכה להסתובב יחד איתו, כך שנראה את מה שהוא רואה.

ב. כשהגעתי להמבורגר, ראיתי מסך לבן.

**Comment by adiy55** [comment]
Fixed issues: Updated camera and added toggle button to switch between views for player preference.

**Comment by erelsgl** [comment]
יותר טוב, אבל עדיין נראה מאד לא טבעי ולא מתאים לתלת-מימד. הכלב מסתכל כל הזמן לאותו כיוון, והולך הצידה. 

בשיעור על עולם תלת-ממדי הסברתי איך לעשות תנועה בעזרת העכבר והמקלדת, כך שהשחקן יוכל להסתובב באופן חופשי, וינוע לכיוון שהוא מסתכל אליו. זה מאד חשוב לצורך חוויית השחקן - לזוז ולפעול כמו כלב.

**Comment by erelsgl** [comment]
בנוסף, אני תקוע במשימות במטבח - לגנוב את האבטיח, ההמבורגר, הגבינה וכו'... זה חוזר על עצמו - לא היו לכם עוד משימות?

**Comment by adiy55** [comment]
היי אראל, 
קודם כל - מאוד נשמח שתסתכל על המשחק המעודכן בitch. 

לגבי המצלמה: יש 2 מצלמות, אחת ממבט עליון ועוד אחת third person המאפשרת תזוזה עם העכבר. אפשר להחליף ביניהן ע"י לחיצה בכפתור מצד ימין למטה.

לגבי המשימות: עדכנו את המשחק עם 3 שלבים עם משימות חדשות.

**Comment by erelsgl** [comment]
הרבה יותר טוב!

א. תוסיפו איפשהו (במסך הפתיחה, בטוטוריאל, בהערות באיטץ', או בכולם) משפט אחד שמגדיר את המשימה העיקרית במשחק כולו, למשל 
"You play a naughty dog. Your job is to wreck havoc on the house without being caught."

ב. עוד רעיונות למשימות: לנבוח ולהבריח את האורחים; לפתוח את הדלת; לברוח החוצה.

ג. האם יש סוף למשחק, או שרק צריך לצבור כמה שיותר נקודות? (אם רוצים סוף למשחק, אפשר להוסיף משימה קשה במיוחד "לברוח החוצה", שאם השחקן הצליח בה, הוא ניצח)

**Comment by adiy55** [comment]
א: הוספנו ברידמי ובitch. 
ב: זה היה חלק מהתכנון שלנו, לצערינו לא הספקנו.
ג: לכל שלב יש סוף - יש זמן מוקצב והמטרה היא לצבור כמה שיותר נקודות. ככל שמסיימים את המשימות יותר מהר, מרוויחים יותר נקודות. בנוסף, יש high score ששומר ומציג לשחקן את הניקוד הכי גבוה שצבר.
